name: CD Workflow
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload result task42.txt on Server    
      uses: appleboy/ssh-action@master
      with: 
        host: brain-client.bigdatateam.org
        username: bdb2c2023q4_guest_3
        key: ${{ secrets.SSH_KEY }}
        script: |
          SEED=200
          result=$(python3 task.py $SEED)
          echo "$result" > task42.txt
          scp task42.txt bdb2c2023q4_guest_3@brain-client.bigdatateam.org:~/bdb2c2023q4_guest_3/Guldana/task42.txt